org: gian2030rosexp
service: api-s3

provider:
  name: aws
  runtime: python3.12
  # Tamaño de memoria por defecto para las funciones (por defecto: 256MB)
  memorySize: 1024
  timeout: 28
  iam:
    role: arn:aws:iam::153620185912:role/LabRole
    # Añadir políticas para operaciones S3
    roleManagedPolicies:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 1024
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
          integration: lambda
  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          integration: lambda
  crear_bucket:
    handler: crear_bucket.lambda_handler
    events:
      - http:
          path: /s3/crear-bucket
          method: post
          cors: true
          integration: lambda
  crear_directorio:
    handler: crear_directorio.lambda_handler
    events:
      - http:
          path: /s3/crear-directorio
          method: post
          cors: true
          integration: lambda
  subir_archivo:
    handler: subir_archivo.lambda_handler
    events:
      - http:
          path: /s3/subir-archivo
          method: post
          cors: true
          integration: lambda